/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BusDiaOrden.java
 *
 * Created on 01-feb-2012, 20:11:35
 */
package Presentacion;

import Datos.CiudadDAO;
import Datos.ClienteDAO;
import Datos.ClienteINFO;
import Datos.ProvinciaDAO;
import Modelo.Ciudad;
import Modelo.Cliente;
import Modelo.Provincia;
import Modelo.Valida;
import java.awt.Dialog;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.combobox.ListComboBoxModel;

/**
 *
 * @author Gisela
 */
public class BusDiaCliente extends javax.swing.JDialog {

    List<Cliente> clientes;
    List<Cliente> clientes1;
    List<Ciudad> ciudades;
    List<Provincia> provincias;
    
    Cliente cliente = new Cliente();
    //Equipo equipo = new Equipo();
    //Cliente cliente = new Cliente();
    String cliente1;
    String idCliente;
    String idCiudad;
    String idProvincia;
    
    int indice;
    ClienteINFO report=new ClienteINFO();
    /** Creates new form BusDiaOrden */
    
    public BusDiaCliente(java.awt.Frame parent) {
        super(parent,"Busqueda de Cliente", true);
        this.constructorInicial();
    }
    
    
    
    public BusDiaCliente(Dialog parent) {
        super(parent,"Busqueda de Cliente", true);
        this.constructorInicial();
    }
    
    private void constructorInicial(){
        
        initComponents();
        this.setLocation(300, 200);        
        this.setSize(600, 500);
        listar();
        this.jComboBox1.setSelectedIndex(-1);
        this.jComboBox2.setSelectedIndex(-1);
        this.jComboBox3.setSelectedIndex(-1);   
       
    }
    
    
    private void listar() {

        try {
           
            clientes = new ArrayList<Cliente>(new ClienteDAO().buscarTodo());
            ciudades = new ArrayList<Ciudad>(new CiudadDAO().buscarTodo());
            provincias = new ArrayList<Provincia>(new ProvinciaDAO().buscarTodo());
           
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

       jComboBox1.setModel(new ListComboBoxModel(clientes));
       jComboBox2.setModel(new ListComboBoxModel(ciudades));
       jComboBox3.setModel(new ListComboBoxModel(provincias));
      

    }
    
    private void cargarTabla() {
        
        ModeloTabla tabla = new ModeloTabla();
        
            clientes1 = new ArrayList<Cliente>(clientes);
        
         

        tabla.addColumn("N° de Cliente");
        tabla.addColumn("Nombre");
        tabla.addColumn("Responsable");
        
        tabla.setRowCount(clientes1.size());

        int i = 0;
        for (Cliente cli : clientes1) {
            tabla.setValueAt(cli.getIdCliente(), i, 0);
            tabla.setValueAt(cli.getNombre(), i, 1);
            tabla.setValueAt(cli.getResponsable(), i, 2);
            
            i++;
        }
        this.jTable1.setModel(tabla);

    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(98, 21));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox1KeyTyped(evt);
            }
        });

        jLabel1.setText("N° Cliente:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Ciudad:");

        jComboBox2.setEditable(true);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setPreferredSize(new java.awt.Dimension(98, 21));

        jLabel4.setText("Cliente:");

        jComboBox3.setEditable(true);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setPreferredSize(new java.awt.Dimension(98, 21));

        jLabel5.setText("Provincia:");

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel13.setText("Resultado:");

        jButton3.setText("Ver informe");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Clientes");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoBuscar48.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel5)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jButton1)
                                .addGap(10, 10, 10)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel1))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
       System.out.println(this.jComboBox1.getSelectedItem()); 
       //verifica el parametro como OT 
       if ((this.jTextField1.getText()).equals("")){
           idCliente =null;
           
      }else{
           idCliente = this.jTextField1.getText();
       
      }
       //verifica el parametro como equipo
       
       if ((this.jComboBox1.getSelectedItem()==null) || this.jComboBox1.getSelectedItem().equals("")){
           
           cliente1 = null;
               
       }else{ 
       
           cliente1=Integer.toString(((Cliente)this.jComboBox1.getSelectedItem()).getIdCliente());
       }
       //verifica el parametro como cliente
       if ((this.jComboBox2.getSelectedItem()==null)|| this.jComboBox2.getSelectedItem().equals("")){
          //cliente = null;
           idCiudad = null;
       }else{
           idCiudad = Integer.toString(((Ciudad)this.jComboBox2.getSelectedItem()).getIdCiudad());
       }
       //verifica el parametro como estado
       System.out.println(this.jComboBox3.getSelectedItem() + "1"); 
       if ((this.jComboBox3.getSelectedItem()==null)||(this.jComboBox3.getSelectedItem().equals(""))){
          idProvincia = null; 
       }else{
                 
          idProvincia = Integer.toString(((Provincia)this.jComboBox3.getSelectedItem()).getIdProvincia());
            }
       
      try {
            
         clientes = new ArrayList<Cliente>(new ClienteDAO().buscar(idCliente, idCiudad, idProvincia));
            
            } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
       cargarTabla();
       this.jButton3.setEnabled(true); 
    }//GEN-LAST:event_jButton1ActionPerformed
  
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int i;

        i= JOptionPane.showConfirmDialog(null,"Desea Salir?","Atención",JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);

        if(i==0) {
            
           dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public int getIndice(){
        return indice;
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        //String fr1=fechaR1.toString();
        //String fr2=fechaR2.toString();
        System.out.println(idCliente);
        System.out.println(idCiudad);
        System.out.println(idProvincia);
        
        
        JDialog viewer = new JDialog(new JDialog(),"Vista previa del reporte", true); 
       
        viewer.setSize(1100,700); 
       
        viewer.setLocationRelativeTo(null); 
        
        //viewer.getContentPane().add(); 
       
        report.startReport(idCliente, idCiudad, idProvincia);
        viewer.getContentPane().add(report.verVisor()); 
        viewer.setVisible(true); 
        this.jButton3.setEnabled(false); 
        //this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyTyped
        
        Character caracter = new Character(evt.getKeyChar());
        System.out.println(caracter+" 44");
        Valida valida = new Valida();

        if (valida.isCaracter(caracter)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jComboBox1KeyTyped
    
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusDiaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusDiaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusDiaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusDiaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                //BusDiaOrden dialog = new BusDiaOrden(new javax.swing.JFrame());
                BusDiaCliente dialog = new BusDiaCliente(new JDialog());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
