/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BusDiaOrden.java
 *
 * Created on 01-feb-2012, 20:11:35
 */
package Presentacion;

import Datos.ClienteDAO;
import Datos.EquipoDAO;
import Datos.OrdenDAO;
import Datos.OrdenINFO;
import Modelo.Cliente;
import Modelo.Equipo;
import Modelo.Orden;
import java.awt.Dialog;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.combobox.ListComboBoxModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
/**
 *
 * @author Gisela
 */
public class BusDiaOrden extends javax.swing.JDialog {

    List<Cliente> clientes;
    List<Orden> ordenes;
    List<Orden> ordenes1;
    List<Equipo> equipos;
  
    Orden orden = new Orden();
    //Equipo equipo = new Equipo();
    //Cliente cliente = new Cliente();
    String idequipo;
    String idcliente;
    String ot;
    String estado;
    String fechaR1;
    String fechaR2;
    String fechaC1;
    String fechaC2;
    String fechaE1;
    String fechaE2;
    int indice;
    OrdenINFO report=new OrdenINFO();
    /** Creates new form BusDiaOrden */
    
    public BusDiaOrden(java.awt.Frame parent) {
        super(parent,"Busqueda de OT", true);        
        this.constructorInicial();
    }
    
    
    
    public BusDiaOrden(Dialog parent) {
        super(parent,"Busqueda de OT", true);
        this.constructorInicial();
    }
    
    private void constructorInicial(){      
        initComponents();
        this.setLocation(300, 150);        
        listar();
        this.jComboBox1.setSelectedIndex(-1);
        this.jComboBox2.setSelectedIndex(-1);
        this.jComboBox3.setSelectedIndex(-1);
        AutoCompleteDecorator.decorate(jComboBox1);
        AutoCompleteDecorator.decorate(jComboBox2);
        AutoCompleteDecorator.decorate(jComboBox3);
        indice = -1;
    }
    
    
    private void listar() {

        try {
            //ordenes = new ArrayList<Orden>(new OrdenDAO().buscarTodo());
            clientes = new ArrayList<Cliente>(new ClienteDAO().buscarTodo());
            equipos = new ArrayList<Equipo>(new EquipoDAO().buscarTodo());
           
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

       jComboBox1.setModel(new ListComboBoxModel(equipos));
       jComboBox2.setModel(new ListComboBoxModel(clientes));
      

    }
    
    private void cargarTabla() {
        
        ModeloTabla tabla = new ModeloTabla();
        
            ordenes1 = new ArrayList<Orden>(ordenes);
        
         

        tabla.addColumn("N° de OT");
        tabla.addColumn("Cliente");
        tabla.addColumn("Fecha de Recepción");
        
        tabla.setRowCount(ordenes1.size());

        int i = 0;
        for (Orden ord : ordenes1) {
            tabla.setValueAt(ord.getIdOrden(), i, 0);
            tabla.setValueAt(ord.getEquipo().getCliente(), i, 1);
            tabla.setValueAt(ord.getFechaRecep(), i, 2);
            
            i++;
        }
        this.jTable1.setModel(tabla);

    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker3 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker4 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker5 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker6 = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("N° OT:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Equipo:");

        jComboBox2.setEditable(true);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Cliente:");

        jComboBox3.setEditable(true);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pendiente", "Concluido", "Entregado" }));

        jLabel5.setText("Estado:");

        jXDatePicker1.setBackground(new java.awt.Color(0, 0, 0));
        jXDatePicker1.setForeground(new java.awt.Color(204, 0, 0));
        jXDatePicker1.setOpaque(true);

        jXDatePicker2.setBackground(new java.awt.Color(0, 0, 0));
        jXDatePicker2.setForeground(new java.awt.Color(204, 0, 0));
        jXDatePicker2.setOpaque(true);

        jXDatePicker3.setBackground(new java.awt.Color(0, 0, 0));
        jXDatePicker3.setForeground(new java.awt.Color(204, 0, 0));
        jXDatePicker3.setOpaque(true);

        jXDatePicker4.setBackground(new java.awt.Color(0, 0, 0));
        jXDatePicker4.setForeground(new java.awt.Color(204, 0, 0));
        jXDatePicker4.setOpaque(true);

        jXDatePicker5.setBackground(new java.awt.Color(0, 0, 0));
        jXDatePicker5.setForeground(new java.awt.Color(204, 0, 0));
        jXDatePicker5.setOpaque(true);

        jXDatePicker6.setBackground(new java.awt.Color(0, 0, 0));
        jXDatePicker6.setForeground(new java.awt.Color(204, 0, 0));
        jXDatePicker6.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("Fechas:");

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Desde:");

        jLabel8.setText("Desde:");

        jLabel9.setText("Desde:");

        jLabel10.setText("Hasta:");

        jLabel11.setText("Hasta:");

        jLabel12.setText("Hasta:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel13.setText("Resultado:");

        jButton3.setText("Ver informe");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ordenes");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoBuscar48.gif"))); // NOI18N

        jLabel15.setText("Recepción");

        jLabel16.setText("Trabajo");

        jLabel17.setText("Entrega");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addGap(4, 4, 4)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4)))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, 118, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, 118, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, 118, Short.MAX_VALUE)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jXDatePicker5, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jXDatePicker3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXDatePicker4, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jXDatePicker6, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jXDatePicker2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14))
                        .addGap(115, 115, 115))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePicker4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePicker6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(jButton3))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
       System.out.println(this.jComboBox1.getSelectedItem()); 
       //verifica el parametro como OT 
       if ((this.jTextField1.getText()).equals("")){
           ot =null;
           //orden.setIdOrden(0);
      }else{
           ot = this.jTextField1.getText();
           //orden.setIdOrden(Integer.parseInt(this.jTextField1.getText()));
      }
       //verifica el parametro como equipo
       if ((this.jComboBox1.getSelectedItem()==null) || this.jComboBox1.getSelectedItem().equals("")){
           //equipo = null;
           idequipo = null;
           //orden.setEquipo(null);    
       }else{ 
           //equipo = (Equipo) this.jComboBox1.getSelectedItem();
           idequipo = Integer.toString(((Equipo) this.jComboBox1.getSelectedItem()).getIdEquipo());
           //orden.setEquipo((Equipo) this.jComboBox1.getSelectedItem());
       }
       //verifica el parametro como cliente
       if ((this.jComboBox2.getSelectedItem()==null)|| this.jComboBox2.getSelectedItem().equals("")){
          //cliente = null;
           idcliente = null;
       }else{
          //cliente = (Cliente)this.jComboBox2.getSelectedItem();
           idcliente = Integer.toString(((Cliente)this.jComboBox2.getSelectedItem()).getIdCliente());
       }
       //verifica el parametro como estado
       System.out.println(this.jComboBox3.getSelectedItem() + "1"); 
       if ((this.jComboBox3.getSelectedItem()==null)||(this.jComboBox3.getSelectedItem().equals(""))){
          estado = null; 
       }else{
          //estado = Integer.toString(((Estado)this.jComboBox3.getSelectedItem()).getIdEstado());
       
          estado = (String)this.jComboBox3.getSelectedItem(); 
          System.out.println(estado);
       }
       //verifica el parametro fecha de recepcion desde 1
       if (this.jXDatePicker1.getDate()==null){
           fechaR1=null;
           //orden.setFechaRecep(null);
       }else{
           fechaR1=convertirFecha1(this.jXDatePicker1.getDate());
           //orden.setFechaRecep(convertirFecha(this.jXDatePicker1.getDate())); 
       }
       //verifica el parametro fecha de recepcion hasta 2
       if (this.jXDatePicker2.getDate()==null){
           fechaR2=null;
       }else{
           fechaR2=convertirFecha1(this.jXDatePicker2.getDate()); 
       }
       //verifica el parametro fecha de concluido desde 1
       if (this.jXDatePicker3.getDate()==null){
           fechaC1=null;
       }else{
           fechaC1=convertirFecha1(this.jXDatePicker3.getDate()); 
       }
       //verifica el parametro fecha de concluido hasta 2
       if (this.jXDatePicker4.getDate()==null){
           fechaC2=null;
       }else{
           fechaC2=convertirFecha1(this.jXDatePicker4.getDate()); 
       }
       //verifica el parametro fecha de entregado desde 1
        if (this.jXDatePicker5.getDate()==null){
           fechaE1=null;
       }else{
           fechaE1=convertirFecha1(this.jXDatePicker5.getDate()); 
       } 
       //verifica el parametro fecha de entregado hasta 2
         if (this.jXDatePicker6.getDate()==null){
           fechaE2=null;
       }else{
           fechaE2=convertirFecha1(this.jXDatePicker6.getDate()); 
       }
       
      // System.out.println(orden.getEquipo());
        
      
        
      
      try {
            ordenes = new ArrayList<Orden>(new OrdenDAO().buscar(ot, idcliente, idequipo, estado, fechaR1, fechaR2, fechaC1, fechaC2, fechaE1, fechaE2));
            
            } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
       cargarTabla();
       this.jButton3.setEnabled(true);  
    }//GEN-LAST:event_jButton1ActionPerformed

    public java.sql.Date convertirFecha (java.util.Date fecha){
        
        java.sql.Date sqlDate1 = new java.sql.Date(fecha.getTime());
        
        return sqlDate1;
    }
    public String convertirFecha1 (java.util.Date fecha){
        System.out.println(fecha);
        java.sql.Date sqlDate1 = new java.sql.Date(fecha.getTime());
        SimpleDateFormat dateFormat = new SimpleDateFormat ("yyyy-MM-dd");
                
//        java.sql.Date sqlDate1 = new java.sql.Date(fecha.getTime());
        
        System.out.println(sqlDate1);
        
        return dateFormat.format(sqlDate1); 
        
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int i;

        i= JOptionPane.showConfirmDialog(null,"Desea Salir?","Atención",JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);

        if(i==0) {
            
           dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public int getIndice(){
        return indice;
    }
    
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
        
        String dato=String.valueOf(this.jTable1.getValueAt(this.jTable1.getSelectedRow(),0));
        indice = (Integer.parseInt (dato)) -1;
        System.out.println(indice);
        //indice = this.jTable1.getSelectedRow();
       
        dispose();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        //String fr1=fechaR1.toString();
        //String fr2=fechaR2.toString();
        System.out.println(ot);
        System.out.println(idequipo);
        System.out.println(idcliente);
        System.out.println(estado);
        System.out.println(fechaR1);
        System.out.println(fechaR2);
        
        JDialog viewer = new JDialog(new JDialog(),"Vista previa del reporte", true); 
       
        viewer.setSize(1100,700); 
       
        viewer.setLocationRelativeTo(null); 
        
        //viewer.getContentPane().add(); 
       
        report.startReport(ot,idequipo,idcliente, estado, fechaR1, fechaR2, fechaC1, fechaC2, fechaE1, fechaE2 );
        viewer.getContentPane().add(report.verVisor()); 
        viewer.show(); 
        this.jButton3.setEnabled(false); 
        //this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusDiaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusDiaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusDiaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusDiaOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                //BusDiaOrden dialog = new BusDiaOrden(new javax.swing.JFrame());
                BusDiaOrden dialog = new BusDiaOrden(new JDialog());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker4;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker5;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker6;
    // End of variables declaration//GEN-END:variables
}
