/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MtoDiaOrden.java
 *
 * Created on 09-dic-2011, 11:11:35
 */
package Presentacion;

import Datos.ClienteDAO;
import Datos.EquipoDAO;
import Datos.OrdenDAO;
import Modelo.Cliente;
import Modelo.Equipo;
import Modelo.Orden;
import Modelo.Usuario;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.combobox.ListComboBoxModel;

/**
 *
 * @author Gisela
 */
public class MtoDiaOrden1 extends java.awt.Dialog implements ItemListener {

    // VER EL CAMBIO DEL USUARIO Y AREA DE TEXTO.... 
    /** Creates new form MtoDiaOrden */
    List<Orden> ordenes;
    List<Equipo> equipos;
    List<Cliente> clientes;
    int indice;
    boolean nuevaorden;
    Orden orden;
    Equipo equipo;
    Usuario usuario;
    String estado1;

    public MtoDiaOrden1(java.awt.Frame parent, Usuario usuario1) {
        super(parent, "Ordenes de Trabajo" + " (" + usuario1.getUsuario() + ")", true);
        usuario = usuario1;
        this.constructorInicial();
    }

    public MtoDiaOrden1(Dialog parent, Usuario usuario1) {
        super(parent, "Ordenes de Trabajo" + " (" + usuario1.getUsuario() + ")", true);
        usuario = usuario1;
        this.constructorInicial();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void constructorInicial() {
        this.setLocation(188, 150);
        initComponents();
        this.btnGrabar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.jComboBox1.setEnabled(false);
        this.jComboBox2.setEnabled(false);
        this.jXDatePicker1.setEnabled(false);
        this.jXDatePicker2.setEnabled(false);
        this.jXDatePicker3.setEnabled(false);
        this.jXDatePicker4.setEnabled(false);
        listar();
        if (ordenes.isEmpty()) {
            indice = 0;
        } else {
            indice = ordenes.size() - 1;
        }
        cargarTexto(indice);
        // System.out.println(indice);
    }

    private void cargarTexto(int indice) {

        if (ordenes.size() > 0) {

            orden = ordenes.get(indice);

            //this.txtUsuario.setText(orden.getUsuario().getUsuario());
            this.txtNumero.setText(Integer.toString(orden.getIdOrden()));
            this.jComboBox1.setSelectedIndex(ordenes.get(indice).getEquipo().getIdEquipo() - 1);
            this.txtDescEquipo.setText(orden.getEquipo().getDescripcion());
            this.jComboBox2.setSelectedIndex(ordenes.get(indice).getEquipo().getCliente().getIdCliente() - 1);
            this.txtRespCliente.setText(orden.getEquipo().getCliente().getResponsable());
            this.txtObservaciones.setText(orden.getObservacion());
            this.txtRemito.setText(orden.getRemito());
            this.jXDatePicker1.setDate(orden.getFechaRecep());
            this.jXDatePicker2.setDate(orden.getFechaLimite());
            this.jXDatePicker3.setDate(orden.getFechaTrabajo());
            this.jXDatePicker4.setDate(orden.getFechaEntrega());
            this.txtUsuario.setText(orden.getUsuario().getUsuario());
            this.txtEstado.setText(orden.getEstado());
            if (this.txtEstado.getText().equals("Pendiente")) {
                this.txtEstado.setBackground(Color.red);
            }
            if (this.txtEstado.getText().equals("Concluido")) {
                this.txtEstado.setBackground(Color.YELLOW);
            }
            if (this.txtEstado.getText().equals("Entregado")) {
                this.txtEstado.setBackground(Color.GREEN);
            }
            estado();


        } else {

            limpiarCajasTexto();
            this.btnEditar.setEnabled(false);
            this.btnGrabar.setEnabled(false);
            this.btnCancelar.setEnabled(false);

        }
    }

    public void estado() {
        if ((jXDatePicker4.getDate()) != null) {
            this.txtEstado.setText("Entregado");
            estado1 = "Entregado";
            this.txtEstado.setBackground(Color.GREEN);
        } else {
            if ((jXDatePicker3.getDate()) != null) {
                this.txtEstado.setText("Concluido");
                estado1 = "Concluido";
                this.txtEstado.setBackground(Color.YELLOW);
            } else {
                if ((jXDatePicker1.getDate()) != null) {
                    this.txtEstado.setText("Pendiente");
                    estado1 = "Pendiente";
                    this.txtEstado.setBackground(Color.red);
                }
            }
        }
    }

    private void listar() {

        try {
            ordenes = new ArrayList<Orden>(new OrdenDAO().buscarTodo());
            equipos = new ArrayList<Equipo>(new EquipoDAO().buscarTodo());
            clientes = new ArrayList<Cliente>(new ClienteDAO().buscarTodo());

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        jComboBox1.setModel(new ListComboBoxModel(equipos));

        jComboBox2.setModel(new ListComboBoxModel(clientes));


    }

    public void limpiarCajasTexto() {

        this.txtNumero.setText("");
        this.jComboBox1.setSelectedIndex(-1);
        this.txtDescEquipo.setText("");
        this.jComboBox2.setSelectedIndex(-1);
        this.txtRespCliente.setText("");
        this.txtObservaciones.setText("");
        this.txtRemito.setText("");
        this.txtUsuario.setText("");
        this.txtEstado.setText("");
        this.jXDatePicker1.setDate(null);
        this.jXDatePicker2.setDate(null);
        this.jXDatePicker3.setDate(null);
        this.jXDatePicker4.setDate(null);
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdelante = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRespCliente = new javax.swing.JTextField();
        txtDescEquipo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jXDatePicker3 = new org.jdesktop.swingx.JXDatePicker();
        jPanel6 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtRemito = new javax.swing.JTextField();
        jXDatePicker4 = new org.jdesktop.swingx.JXDatePicker();
        jPanel9 = new javax.swing.JPanel();
        txtEstado = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(880, 560));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(null);

        btnAdelante.setText(">");
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdelante);
        btnAdelante.setBounds(380, 440, 108, 36);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(380, 480, 108, 36);

        btnNuevo.setText(" Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo);
        btnNuevo.setBounds(50, 440, 108, 36);

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrabar);
        btnGrabar.setBounds(160, 440, 108, 36);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);
        btnEditar.setBounds(50, 480, 108, 36);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(160, 480, 108, 36);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setText("N° de OT:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 30, 116, 29);

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 24));
        txtNumero.setForeground(new java.awt.Color(153, 153, 255));
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero.setText("2011");
        txtNumero.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNumero.setEnabled(false);
        jPanel1.add(txtNumero);
        txtNumero.setBounds(420, 30, 127, 35);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("N° de Equipo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 106, 86, 24);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Descripción");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 110, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Cliente");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 180, 60, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Responsable");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 180, 80, 20);

        txtRespCliente.setText("ADRIAN GENOVA");
        txtRespCliente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtRespCliente.setEnabled(false);
        jPanel1.add(txtRespCliente);
        txtRespCliente.setBounds(200, 200, 320, 20);

        txtDescEquipo.setText("NOTEBOOK");
        txtDescEquipo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescEquipo.setEnabled(false);
        jPanel1.add(txtDescEquipo);
        txtDescEquipo.setBounds(200, 130, 320, 20);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Equipos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("...");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(680, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 90, 870, 70);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Clientes"));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(686, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 160, 870, 70);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Recepción"));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setText("Fecha de Recepción:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("Fecha Limite:");

        jXDatePicker1.setBackground(new java.awt.Color(0, 0, 0));
        jXDatePicker1.setForeground(new java.awt.Color(204, 0, 0));
        jXDatePicker1.setOpaque(true);

        jXDatePicker2.setBackground(new java.awt.Color(255, 255, 255));
        jXDatePicker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 230, 240, 90);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Servicio"));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setText("Fecha del servicio:");

        jXDatePicker3.setBackground(new java.awt.Color(255, 255, 255));
        jXDatePicker3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addComponent(jXDatePicker3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jXDatePicker3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(240, 230, 230, 90);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

        txtUsuario.setText("JLENCINA");
        txtUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtUsuario.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(660, 430, 210, 90);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Observaciones"));

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        txtObservaciones.setEnabled(false);
        jScrollPane1.setViewportView(txtObservaciones);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 330, 870, 90);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrega"));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel14.setText("Remito:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel15.setText("Fecha entrega:");

        txtRemito.setText("01-1001");
        txtRemito.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtRemito.setEnabled(false);

        jXDatePicker4.setBackground(new java.awt.Color(255, 255, 255));
        jXDatePicker4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePicker4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXDatePicker4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(txtRemito, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jXDatePicker4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(470, 230, 220, 90);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));

        txtEstado.setEditable(false);
        txtEstado.setFont(new java.awt.Font("Tahoma", 1, 24));
        txtEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(690, 230, 180, 90);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar);
        btnBuscar.setBounds(270, 480, 108, 36);

        btnAtras.setText("<");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras);
        btnAtras.setBounds(270, 440, 108, 36);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int i;

        i = JOptionPane.showConfirmDialog(null, "Desea Salir?", "Atención", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

        if (i == 0) {

            dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    public java.sql.Date convertirFecha(java.util.Date fecha) {

        java.sql.Date sqlDate1 = new java.sql.Date(fecha.getTime());

        return sqlDate1;
    }

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed

        OrdenDAO norden = new OrdenDAO();

        if (nuevaorden == true) {
            if (jComboBox1.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "¡Selecciones un item!", "Error", JOptionPane.ERROR_MESSAGE);
                jComboBox1.showPopup();

            } else {
                if (this.jXDatePicker2.getDate() == null) {
                    JOptionPane.showMessageDialog(null, "¡Faltan Completar Datos!", "Error", JOptionPane.ERROR_MESSAGE);
                    this.jXDatePicker2.requestFocus();

                } else {
                    orden.setUsuario(usuario);
                    orden.setEquipo((Equipo) this.jComboBox1.getSelectedItem());
                    orden.setFechaRecep(convertirFecha(this.jXDatePicker1.getDate()));
                    //System.out.println(estado1);
                    orden.setEstado(estado1);
                    //System.out.println(this.txtEstado.getText());
                    orden.setFechaLimite(convertirFecha(this.jXDatePicker2.getDate()));
                    orden.setFechaTrabajo(null);
                    orden.setFechaEntrega(null);
                    orden.setObservacion(this.txtObservaciones.getText());
                    orden.setRemito(null);
                    //System.out.println(orden);
                    try {
                        norden.agregar(orden);
                    } catch (SQLException ex) {
                        Logger.getLogger(MtoDiaCiudad1_2.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    listar();
                    indice = (ordenes.size() - 1);
                    cargarTexto(indice);


                    this.btnEditar.setEnabled(true);
                    this.btnGrabar.setEnabled(false);
                    this.btnCancelar.setEnabled(false);
                    this.btnNuevo.setEnabled(true);
                    this.btnAtras.setEnabled(true);
                    this.btnAdelante.setEnabled(true);
                    this.btnBuscar.setEnabled(true);
                    this.jComboBox1.setEnabled(false);
                    this.jComboBox2.setEnabled(false);
                    this.jXDatePicker2.setEnabled(false);
                    this.jButton1.setEnabled(false);
                    this.txtObservaciones.setEnabled(false);
                }
            }
        } else {

            orden = ordenes.get(indice);
            
                if ((this.jXDatePicker3.isEnabled() == true)&(this.jXDatePicker3.getDate() == null)) {
                    JOptionPane.showMessageDialog(null, "¡Faltan Completar Datos 1!", "Error", JOptionPane.ERROR_MESSAGE);
                    this.jXDatePicker3.requestFocus();
                }else{
              if ((this.txtRemito.isEnabled()==true)&(this.txtRemito.getText().isEmpty())){
                    JOptionPane.showMessageDialog(null, "¡Faltan Completar Datos 2!", "Error", JOptionPane.ERROR_MESSAGE);
                    this.txtRemito.requestFocus();
                } else {
                    if ((this.jXDatePicker4.isEnabled()==true)&(this.jXDatePicker4.getDate() == null)) {
                        JOptionPane.showMessageDialog(null, "¡Faltan Completar Datos 3!", "Error", JOptionPane.ERROR_MESSAGE);
                        this.jXDatePicker4.requestFocus();
                    } else {
            orden.setIdOrden(Integer.parseInt(this.txtNumero.getText()));
            orden.setUsuario(usuario);
            orden.setEquipo((Equipo) this.jComboBox1.getSelectedItem());
            java.util.Date utilDate = this.jXDatePicker3.getDate();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            orden.setFechaTrabajo(sqlDate);
            orden.setEstado(estado1);
            if (this.jXDatePicker4.getDate() == null) {
                orden.setFechaEntrega(null);
            } else {
                java.util.Date utilDate1 = this.jXDatePicker4.getDate();
                java.sql.Date sqlDate1 = new java.sql.Date(utilDate1.getTime());
                orden.setFechaEntrega(sqlDate1);
            }
            orden.setObservacion(this.txtObservaciones.getText());
            orden.setRemito(this.txtRemito.getText());


            try {
                norden.actualizar(orden);
            } catch (SQLException ex) {
                Logger.getLogger(MtoDiaCiudad1_2.class.getName()).log(Level.SEVERE, null, ex);
            }


            this.cargarTexto(indice);

            this.btnNuevo.setEnabled(true);
            this.btnEditar.setEnabled(true);
            this.btnAtras.setEnabled(true);
            this.btnAdelante.setEnabled(true);
            this.btnBuscar.setEnabled(true);
            this.btnGrabar.setEnabled(false);
            this.btnCancelar.setEnabled(false);
            this.jComboBox1.setEnabled(false);
            this.jComboBox1.setEnabled(false);
            this.jXDatePicker3.setEnabled(false);
            this.jXDatePicker4.setEnabled(false);
            this.txtRemito.setEnabled(false);
            this.jButton1.setEnabled(false);
            this.txtObservaciones.setEnabled(false);
            }
            }
          }
       }
    
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarCajasTexto();
        nuevaorden = true;
        this.listar();
        this.jComboBox1.setEnabled(true);
        this.jComboBox1.setSelectedIndex(-1);
        this.jComboBox2.setEnabled(false);
        this.jComboBox2.setSelectedIndex(-1);
        this.btnNuevo.setEnabled(false);
        this.btnAtras.setEnabled(false);
        this.btnAdelante.setEnabled(false);
        this.btnBuscar.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnGrabar.setEnabled(true);
        this.btnCancelar.setEnabled(true);
        this.txtNumero.setEditable(false);
        this.jXDatePicker1.setEnabled(true);
        Date fecha = new Date();
        this.jXDatePicker1.setDate(fecha);
        this.jXDatePicker1.setEnabled(false);
        this.jXDatePicker2.setEnabled(true);
        this.jComboBox1.addItemListener(this);
        this.txtObservaciones.setEnabled(true);
        this.txtEstado.setBackground(Color.WHITE);
        this.jButton1.setEnabled(true);

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (this.jXDatePicker4.getDate() != null) {
            JOptionPane.showMessageDialog(null, "¡Esta Orden de Trabajo esta Entregada!", "Atención", JOptionPane.INFORMATION_MESSAGE);
            this.btnNuevo.requestFocus();
        } else {
            nuevaorden = false;
            this.jComboBox1.setEnabled(false);
            this.jComboBox2.setEnabled(false);
            this.btnNuevo.setEnabled(false);
            this.btnEditar.setEnabled(false);
            this.btnGrabar.setEnabled(true);
            this.btnBuscar.setEnabled(false);
            this.btnAdelante.setEnabled(false);
            this.btnAtras.setEnabled(false);
            this.btnCancelar.setEnabled(true);
            this.jXDatePicker1.setEnabled(false);
            this.jXDatePicker2.setEnabled(false);

            if (this.jXDatePicker1.getDate() != null) {
                this.jXDatePicker3.setEnabled(true);
                this.jXDatePicker4.setEnabled(false);
                this.txtObservaciones.setEnabled(true);
            }
            if (this.jXDatePicker3.getDate() != null) {
                this.jXDatePicker3.setEnabled(false);
                this.txtRemito.setEnabled(true);
                this.jXDatePicker4.setEnabled(true);
                
                this.txtObservaciones.setEnabled(true);
                

            }

        }



    }//GEN-LAST:event_btnEditarActionPerformed

    private void jXDatePicker3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker3ActionPerformed
        if ((this.jXDatePicker3.getDate()).after(this.jXDatePicker2.getDate()) | (this.jXDatePicker3.getDate()).before(this.jXDatePicker1.getDate())) {

            JOptionPane.showMessageDialog(null, "La fecha debe estar comprendida entre la fecha de recepcion y limite...", "Información", JOptionPane.INFORMATION_MESSAGE);
            this.jXDatePicker3.setDate(null);

        }
        estado();
    }//GEN-LAST:event_jXDatePicker3ActionPerformed

    private void jXDatePicker4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker4ActionPerformed
        if ((this.jXDatePicker4.getDate()).after(this.jXDatePicker2.getDate()) | (this.jXDatePicker4.getDate()).before(this.jXDatePicker1.getDate())) {

            JOptionPane.showMessageDialog(null, "La fecha es inferior a la fecha Recepción o supera la fecha limite...", "Información", JOptionPane.INFORMATION_MESSAGE);
            this.jXDatePicker4.setDate(null);

        }
        estado();
    }//GEN-LAST:event_jXDatePicker4ActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed

        if (indice == 0) {
            JOptionPane.showMessageDialog(null, "No hay mas registros...", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            indice = --indice;
            System.out.println(indice);
            this.cargarTexto(indice);
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        if (indice == ordenes.size() - 1) {
            JOptionPane.showMessageDialog(null, "No hay mas registros...", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            indice = ++indice;
            System.out.println(indice);
            this.cargarTexto(indice);
        }
    }//GEN-LAST:event_btnAdelanteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (ordenes.size() > 0) {

            if (nuevaorden == true) {

                this.cargarTexto(indice);
                this.listar();
                this.jComboBox1.setEnabled(false);
                this.jComboBox2.setEnabled(false);
                this.btnNuevo.setEnabled(true);
                this.btnAtras.setEnabled(true);
                this.btnAdelante.setEnabled(true);
                this.btnBuscar.setEnabled(true);
                this.btnEditar.setEnabled(true);
                this.btnGrabar.setEnabled(false);
                this.btnCancelar.setEnabled(false);
                this.txtObservaciones.setEnabled(false);
                this.txtNumero.setEditable(true);
                this.jXDatePicker1.setEnabled(false);
                Date fecha = new Date();
                this.jXDatePicker1.setDate(fecha);
                this.jXDatePicker1.setEnabled(false);
                this.jXDatePicker2.setEnabled(false);
                this.jComboBox1.addItemListener(this);

                if (ordenes.size() > 0) {
                    this.btnEditar.setEnabled(true);
                } else {
                    this.btnEditar.setEnabled(false);
                }
                this.jButton1.setEnabled(false);
            } else {

                this.cargarTexto(indice);
                this.jComboBox1.setEnabled(false);
                this.jComboBox2.setEnabled(false);
                this.btnNuevo.setEnabled(true);
                this.btnEditar.setEnabled(true);
                this.btnGrabar.setEnabled(false);
                this.btnBuscar.setEnabled(true);
                this.btnAdelante.setEnabled(true);
                this.btnAtras.setEnabled(true);
                this.btnCancelar.setEnabled(false);
                this.jXDatePicker1.setEnabled(false);
                this.jXDatePicker2.setEnabled(false);

                if (this.jXDatePicker2.getDate() != null) {
                    this.jXDatePicker3.setEnabled(false);
                    this.jXDatePicker4.setEnabled(false);
                    
                }
                if (this.jXDatePicker3.getDate() != null) {
                    this.jXDatePicker3.setEnabled(false);
                    this.jXDatePicker4.setEnabled(false);
                    this.txtRemito.setEnabled(false);

                }
                this.txtObservaciones.setEnabled(false);
                //this.jButton1.setEnabled(false);
            }
        } else {
            limpiarCajasTexto();
            this.btnEditar.setEnabled(false);
            this.btnGrabar.setEnabled(false);
            this.btnCancelar.setEnabled(false);
            this.jComboBox1.setEnabled(false);

        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jXDatePicker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePicker2ActionPerformed

        if ((this.jXDatePicker2.getDate()).before(this.jXDatePicker1.getDate())) {
            JOptionPane.showMessageDialog(null, "La fecha debe ser mayor que la fecha de Recepción...", "Información", JOptionPane.INFORMATION_MESSAGE);
            this.jXDatePicker2.setDate(null);
        }
    }//GEN-LAST:event_jXDatePicker2ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        BusDiaOrden bus = new BusDiaOrden(this);
        bus.setVisible(true);
        if (bus.getIndice()!=-1){
        indice = bus.getIndice();
        }
        listar();
        this.cargarTexto(indice);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MtoDiaEquipo1 nuevoEqui = new MtoDiaEquipo1(this);
        nuevoEqui.setVisible(true);
        this.listar();
        this.jComboBox1.setSelectedIndex(-1);
    }//GEN-LAST:event_jButton1ActionPerformed

    @Override
    public void itemStateChanged(ItemEvent e) {
        if (e.getStateChange() == ItemEvent.SELECTED) {
            txtDescEquipo.setText(((Equipo) jComboBox1.getSelectedItem()).getDescripcion());
            jComboBox2.setSelectedIndex(((Equipo) jComboBox1.getSelectedItem()).getCliente().getIdCliente() - 1);
            txtRespCliente.setText(((Cliente) jComboBox2.getSelectedItem()).getResponsable());
            estado();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                // MtoDiaOrden dialog = new MtoDiaOrden(new java.awt.Frame());
                MtoDiaOrden1 dialog = new MtoDiaOrden1(new JDialog(), new Usuario());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker4;
    private javax.swing.JTextField txtDescEquipo;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtRemito;
    private javax.swing.JTextField txtRespCliente;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
