/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MtoDiaCiudad1.java
 *
 * Created on 04-oct-2011, 18:34:42
 */
package Presentacion;

import Datos.UsuarioDAO;
import Modelo.Usuario;
import Modelo.Valida;
import java.awt.Dialog;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Gisela
 */
public class MtoDiaUsuario extends java.awt.Dialog {

    /** Creates new form MtoDiaCiudad1 */
    List<Usuario> usuarios;
    int indice;
    boolean nuevousuario;
    boolean habilitaclick;
    Usuario usuario;

    public MtoDiaUsuario(Dialog parent) {

        super(parent, "USUARIOS", true);
        constructorInicial();
    }

    public MtoDiaUsuario(java.awt.Frame parent) {

        super(parent, "USUARIOS", true);
        constructorInicial();
    }

    private void constructorInicial() {
        initComponents();
        this.setLocation(300, 200);
        this.setSize(600, 500);
        this.cargarTabla();
        this.cargarTexto(0);
        this.setResizable(false);
        this.btnGrabar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        usuario = new Usuario();
        indice = 0;
        btnNuevo.requestFocus();
        //this.txtpassContraseña.setEchoChar(' ');
    }

    private void cargarTexto(int indice) {

        if (usuarios.size() > 0) {
            this.btnEditar.setEnabled(true);
            usuario = usuarios.get(indice);
            this.txtIdUsuario.setText(Integer.toString(usuario.getIdUsuario()));
            this.txtNombreUsuario.setText(usuario.getUsuario());
            this.txtpassContraseña.setText(usuario.getPassword());
            this.txtApellido.setText(usuario.getApellido());
            this.txtNombre.setText(usuario.getNombre());

        } else {
            limpiarCajasTexto();
            this.btnEditar.setEnabled(false);

        }
        txtNombreUsuario.setEnabled(false);
        txtpassContraseña.setEnabled(false);
        txtApellido.setEnabled(false);
        txtNombre.setEnabled(false);


    }

    private void cargarTabla() {


        ModeloTabla tabla = new ModeloTabla();

        try {
            usuarios = new ArrayList<Usuario>(new UsuarioDAO().buscarTodo());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        tabla.addColumn("Id Usuario");
        tabla.addColumn("Nombre de Usuario");
        tabla.addColumn("Contraseña");
        tabla.addColumn("Apellido");
        tabla.addColumn("Nombre");
        tabla.setRowCount(usuarios.size());

        int i = 0;
        for (Usuario usu : usuarios) {
            tabla.setValueAt(usu.getIdUsuario(), i, 0);
            tabla.setValueAt(usu.getUsuario(), i, 1);
            tabla.setValueAt(usu.getPassword(), i, 2);
            tabla.setValueAt(usu.getApellido(), i, 3);
            tabla.setValueAt(usu.getNombre(), i, 4);
            i++;
        }
        this.jTable1.setModel(tabla);

    }

    public void limpiarCajasTexto() {

        this.txtIdUsuario.setText("");
        this.txtNombreUsuario.setText("");
        txtpassContraseña.setText("");
        txtApellido.setText("");
        txtNombre.setText("");
    }

    private void habilitacajatexto(boolean hab) {
        txtNombreUsuario.setEnabled(hab);
        txtpassContraseña.setEnabled(hab);
        txtApellido.setEnabled(hab);
        txtNombre.setEnabled(hab);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEditar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();
        btnNuevo = new javax.swing.JToggleButton();
        btnGrabar = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        txtIdUsuario = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpassContraseña = new javax.swing.JPasswordField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setMinimumSize(new java.awt.Dimension(675, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/consultar.gif"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setNextFocusableComponent(btnGrabar);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cancelar.gif"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setNextFocusableComponent(txtNombreUsuario);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/componente_agregar.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("");
        btnNuevo.setNextFocusableComponent(btnEditar);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/guardar.gif"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.setNextFocusableComponent(btnCancelar);
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DE USUARIOS"));

        txtIdUsuario.setText("jTextField1");
        txtIdUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtIdUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIdUsuario.setEnabled(false);

        txtNombreUsuario.setText("jTextField2");
        txtNombreUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombreUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombreUsuario.setEnabled(false);
        txtNombreUsuario.setNextFocusableComponent(txtpassContraseña);

        txtApellido.setText("jTextField3");
        txtApellido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtApellido.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtApellido.setEnabled(false);
        txtApellido.setNextFocusableComponent(txtNombre);

        jLabel1.setText("Id Usuario:");

        jLabel2.setText("Nombre de Usuario:");

        jLabel3.setText("Contraseña:");

        jLabel4.setText("Apellido:");

        txtNombre.setText("jTextField3");
        txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombre.setEnabled(false);
        txtNombre.setNextFocusableComponent(btnNuevo);

        jLabel5.setText("Nombre:");

        txtpassContraseña.setText("jPasswordField1");
        txtpassContraseña.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtpassContraseña.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtpassContraseña.setEnabled(false);
        txtpassContraseña.setNextFocusableComponent(txtApellido);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(txtIdUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(txtpassContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtpassContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(habilitaclick==true){
           
       }else{ 
        indice = this.jTable1.getSelectedRow();
        usuario = usuarios.get(indice);
        this.cargarTexto(indice);
        }   
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        nuevousuario = false;
        habilitaclick=true;
        this.btnNuevo.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnGrabar.setEnabled(true);
        this.btnCancelar.setEnabled(true);
        this.habilitacajatexto(true);
        this.jTable1.setEnabled(false);
        this.txtNombreUsuario.requestFocus();
}//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (nuevousuario == true) {
            this.cargarTexto(indice);
            this.btnNuevo.setEnabled(true);
            this.btnCancelar.setEnabled(false);
            this.btnGrabar.setEnabled(false);
            if (usuarios.size() > 0) {
                this.btnEditar.setEnabled(true);
            } else {
                this.btnEditar.setEnabled(false);
            }
        } else {

            this.cargarTexto(indice);
            this.btnNuevo.setEnabled(true);
            this.btnEditar.setEnabled(true);
            this.btnGrabar.setEnabled(false);
            this.btnCancelar.setEnabled(false);
        }     
        this.habilitacajatexto(false);
        this.jTable1.setEnabled(true);
        habilitaclick = false;
}//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarCajasTexto();
        nuevousuario = true;
        this.btnNuevo.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnGrabar.setEnabled(true);
        this.btnCancelar.setEnabled(true);
        this.habilitacajatexto(true);
        this.jTable1.setEnabled(false);
        this.txtNombreUsuario.requestFocus();
        habilitaclick = true;        
}//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        UsuarioDAO nusuario = new UsuarioDAO();
        Valida validar = new Valida();
        if (nuevousuario == true) {
            usuario = new Usuario();

            if (validar.isCampoVacio(txtNombreUsuario.getText())) {
                JOptionPane.showMessageDialog(null, "¡Faltan Completar Datos!", "Error", JOptionPane.ERROR_MESSAGE);
                txtNombreUsuario.requestFocus();
            } else {
                if (validar.isCampoVacio(txtpassContraseña.getText())) {
                    JOptionPane.showMessageDialog(null, "¡Faltan Completar Datos!", "Error", JOptionPane.ERROR_MESSAGE);
                    txtpassContraseña.requestFocus();
                } else {

                    if (validar.isCampoVacio(txtApellido.getText())) {
                        JOptionPane.showMessageDialog(null, "¡Faltan Completar Datos!", "Error", JOptionPane.ERROR_MESSAGE);
                        txtApellido.requestFocus();
                    } else {
                        if (validar.isCampoVacio(txtNombre.getText())) {
                            JOptionPane.showMessageDialog(null, "¡Faltan Completar Datos!", "Error", JOptionPane.ERROR_MESSAGE);
                            txtNombre.requestFocus();
                        } else {

                            usuario.setUsuario(this.txtNombreUsuario.getText());
                            usuario.setPassword(this.txtpassContraseña.getText());
                            usuario.setApellido(this.txtApellido.getText());
                            usuario.setNombre(this.txtNombre.getText());

                            try {
                                nusuario.agregar(usuario);
                            } catch (SQLException ex) {
                                Logger.getLogger(MtoDiaUsuario.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            this.cargarTabla();
                            indice = (usuarios.size() - 1);
                            this.cargarTexto(indice);
                            this.btnNuevo.setEnabled(true);
                            this.btnEditar.setEnabled(true);
                            this.btnGrabar.setEnabled(false);
                            this.btnCancelar.setEnabled(false);
                            this.habilitacajatexto(false);  
                            this.jTable1.setEnabled(true);
                            habilitaclick=false;
                        }
                    }
                }
            }
        } else {


            if (validar.isCampoVacio(txtNombreUsuario.getText())) {
                JOptionPane.showMessageDialog(null, "¡Faltan Completar Datos!", "Error", JOptionPane.ERROR_MESSAGE);
                txtNombreUsuario.requestFocus();
            } else {
                if (validar.isCampoVacio(txtpassContraseña.getText())) {
                    JOptionPane.showMessageDialog(null, "¡Faltan Completar Datos!", "Error", JOptionPane.ERROR_MESSAGE);
                    txtpassContraseña.requestFocus();
                } else {

                    if (validar.isCampoVacio(txtApellido.getText())) {
                        JOptionPane.showMessageDialog(null, "¡Faltan Completar Datos!", "Error", JOptionPane.ERROR_MESSAGE);
                        txtApellido.requestFocus();
                    } else {
                        if (validar.isCampoVacio(txtNombre.getText())) {
                            JOptionPane.showMessageDialog(null, "¡Faltan Completar Datos!", "Error", JOptionPane.ERROR_MESSAGE);
                            txtNombre.requestFocus();
                        } else {


                            usuario.setIdUsuario(Integer.parseInt(this.txtIdUsuario.getText()));
                            usuario.setUsuario(this.txtNombreUsuario.getText());
                            usuario.setPassword(this.txtpassContraseña.getText());
                            usuario.setApellido(this.txtApellido.getText());
                            usuario.setNombre(this.txtNombre.getText());

                            try {
                               nusuario.actualizar(usuario);
                            } catch (SQLException ex) {
                                // VER ESTO EN LOS FORMULARIOS!!
                                Logger.getLogger(MtoDiaUsuario.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            this.cargarTabla();
                            this.cargarTexto(indice);
                            this.habilitacajatexto(false);
                            this.btnNuevo.setEnabled(true);
                            this.btnEditar.setEnabled(true);
                            this.btnGrabar.setEnabled(false);
                            this.btnCancelar.setEnabled(false);
                            this.jTable1.setEnabled(true);
                            habilitaclick=false;
                        }
                    }
                }
}//GEN-LAST:event_btnGrabarActionPerformed
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MtoDiaUsuario dialog = new MtoDiaUsuario(new JDialog());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JToggleButton btnGrabar;
    private javax.swing.JToggleButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtpassContraseña;
    // End of variables declaration//GEN-END:variables
}
