/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MtoDiaCiudad1.java
 *
 * Created on 04-oct-2011, 18:34:42
 */
package Presentacion;

import Datos.CiudadDAO;
import Datos.ProvinciaDAO;
import Modelo.Ciudad;
import Modelo.Provincia;
import Modelo.Valida;
import java.awt.Color;
import java.awt.Dialog;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.combobox.ListComboBoxModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Gisela
 */
public class MtoDiaCiudad1_2 extends java.awt.Dialog {

    /** Creates new form MtoDiaCiudad1 */
    List<Ciudad> ciudades;
    List<Provincia> provincias;
    int indice;
    boolean nuevaciudad;
    boolean habilitaclick;
    Ciudad ciudad;

    public MtoDiaCiudad1_2(Dialog parent) {

        super(parent, "CIUDADES", true);
        initComponents();
        this.setLocation(300, 200);
        this.setSize(600, 500);
        this.cargarTabla();
        this.listarJcombo();
        this.cargarTexto(0);
        this.setResizable(false);
        this.btnGrabar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.jComboBox1.setBackground(Color.WHITE);
        ciudad = new Ciudad();
        indice = 0;
        AutoCompleteDecorator.decorate(jComboBox1);
        btnNuevo.requestFocus();
        //this.setVisible(true);
    }

    private void cargarTexto(int indice) {

        if (ciudades.size() > 0) {
            this.btnEditar.setEnabled(true);
            ciudad = ciudades.get(indice);
            this.txtCodigo.setText(Integer.toString(ciudad.getIdCiudad()));
            this.txtNombre.setText(ciudad.getCiudad());
            this.txtCP.setText(Integer.toString(ciudad.getCp()));
            this.jComboBox1.setSelectedIndex(ciudades.get(indice).getProvincia().getIdProvincia() - 1);

        } else {
            limpiarCajasTexto();
            this.btnEditar.setEnabled(false);
               }
       }

    private void listarJcombo() {

        try {
            provincias = new ArrayList<Provincia>(new ProvinciaDAO().buscarTodo());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        jComboBox1.setModel(new ListComboBoxModel(provincias));
    }

    private void cargarTabla() {
       
        ModeloTabla tabla = new ModeloTabla();

        try {
            ciudades = new ArrayList<Ciudad>(new CiudadDAO().buscarTodo());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        tabla.addColumn("Id Ciudad");
        tabla.addColumn("Nombre");
        tabla.addColumn("Codigo Postal");
        tabla.addColumn("Provincia");
        tabla.setRowCount(ciudades.size());

        int i = 0;
        for (Ciudad ciud : ciudades) {
            tabla.setValueAt(ciud.getIdCiudad(), i, 0);
            tabla.setValueAt(ciud.getCiudad(), i, 1);
            tabla.setValueAt(ciud.getCp(), i, 2);
            tabla.setValueAt(ciud.getProvincia().getProvincia(), i, 3);
            i++;
        }
        this.jTable1.setModel(tabla);

    }

    public void limpiarCajasTexto() {

        this.txtCodigo.setText("");
        this.txtNombre.setText("");
        this.txtCP.setText("");
        this.jComboBox1.setSelectedIndex(-1);

    }
    
    private void habilitacajatexto(boolean hab){
        txtNombre.setEnabled(hab);
        txtCP.setEnabled(hab);
        this.jComboBox1.setEnabled(hab);      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEditar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();
        btnNuevo = new javax.swing.JToggleButton();
        btnGrabar = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setMinimumSize(new java.awt.Dimension(675, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/consultar.gif"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setNextFocusableComponent(btnGrabar);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cancelar.gif"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setNextFocusableComponent(txtNombre);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/componente_agregar.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("");
        btnNuevo.setNextFocusableComponent(btnEditar);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/guardar.gif"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.setNextFocusableComponent(btnCancelar);
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DE CIUDADES"));

        txtCodigo.setText("jTextField1");
        txtCodigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigo.setEnabled(false);

        txtNombre.setText("jTextField2");
        txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombre.setEnabled(false);
        txtNombre.setNextFocusableComponent(txtCP);

        txtCP.setText("jTextField3");
        txtCP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCP.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCP.setEnabled(false);
        txtCP.setNextFocusableComponent(jComboBox1);
        txtCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPKeyTyped(evt);
            }
        });

        jLabel1.setText("Id Ciudad:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Codigo postal:");

        jLabel4.setText("Provincia:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox1.setEnabled(false);
        jComboBox1.setNextFocusableComponent(btnGrabar);
        jComboBox1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(txtCP, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        if(habilitaclick==true){
           
       }else{
        indice = this.jTable1.getSelectedRow();
        ciudad = ciudades.get(indice);
        this.cargarTexto(indice);
            }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        nuevaciudad = false;
        habilitaclick = true;
        this.btnEditar.setEnabled(false);
        this.btnNuevo.setEnabled(false);
        this.btnGrabar.setEnabled(true);
        this.btnCancelar.setEnabled(true);
        this.habilitacajatexto(true);
        this.jTable1.setEnabled(false);
        this.txtNombre.requestFocus();
        

}//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        if (nuevaciudad == true) {
            this.listarJcombo();
            this.cargarTexto(indice);
            this.btnNuevo.setEnabled(true);
            this.btnCancelar.setEnabled(false);
            this.btnGrabar.setEnabled(false);
            if (ciudades.size() > 0) {
                this.btnEditar.setEnabled(true);
            } else {
                this.btnEditar.setEnabled(false);
            }
        } else {

            this.cargarTexto(indice);
            this.btnNuevo.setEnabled(true);
            this.btnEditar.setEnabled(true);
            this.btnGrabar.setEnabled(false);
            this.btnCancelar.setEnabled(false);

        }
        this.habilitacajatexto(false);
        this.jTable1.setEnabled(true);
        this.btnNuevo.requestFocus();
        habilitaclick = false;
}//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        limpiarCajasTexto();
        nuevaciudad = true;
        this.listarJcombo();
        this.jComboBox1.setSelectedIndex(-1);
        this.btnNuevo.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnGrabar.setEnabled(true);
        this.btnCancelar.setEnabled(true);
        this.habilitacajatexto(true);
        this.jTable1.setEnabled(false);
        txtNombre.requestFocus();
        habilitaclick=true;
}//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed


        CiudadDAO nciudad = new CiudadDAO();
        Valida validar = new Valida();
        if (nuevaciudad == true) {
            ciudad = new Ciudad();

            if (validar.isCampoVacio(txtNombre.getText())) {
                JOptionPane.showMessageDialog(null,"¡Faltan Completar Datos!","Error" , JOptionPane.ERROR_MESSAGE);
                txtNombre.requestFocus();
            } else {
                if (validar.isCampoVacio(txtCP.getText())) {
                    JOptionPane.showMessageDialog(null,"¡Faltan Completar Datos!","Error" , JOptionPane.ERROR_MESSAGE);
                    txtCP.requestFocus();
                } else {
                    if (jComboBox1.getSelectedIndex() == -1) {
                        JOptionPane.showMessageDialog(null, "¡Selecciones un item!","Error" , JOptionPane.ERROR_MESSAGE);
                        jComboBox1.showPopup();

                    } else {
                        ciudad.setCiudad(this.txtNombre.getText());
                        ciudad.setCp(Integer.parseInt(this.txtCP.getText()));
                        ciudad.setProvincia((Provincia) this.jComboBox1.getSelectedItem());
                        try {
                            nciudad.agregar(ciudad);
                        } catch (SQLException ex) {
                            Logger.getLogger(MtoDiaCiudad1_2.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        this.cargarTabla();
                        indice = (ciudades.size() - 1);
                        this.cargarTexto(indice);
                        this.btnNuevo.setEnabled(true);
                        this.btnEditar.setEnabled(true);
                        this.btnGrabar.setEnabled(false);
                        this.btnCancelar.setEnabled(false);
                        this.habilitacajatexto(false);
                        this.jTable1.setEnabled(true);
                        habilitaclick = false;
                    }
                }
            }

        } else {
        
            if (validar.isCampoVacio(txtNombre.getText())) {
                JOptionPane.showMessageDialog(null,"¡Faltan Completar Datos!","Error" , JOptionPane.ERROR_MESSAGE);
                txtNombre.requestFocus();
            } else {
                if (validar.isCampoVacio(txtCP.getText())) {
                    JOptionPane.showMessageDialog(null,"¡Faltan Completar Datos!","Error" , JOptionPane.ERROR_MESSAGE);
                    txtCP.requestFocus();
                } else {
                    if (jComboBox1.getSelectedIndex() == -1) {
                        JOptionPane.showMessageDialog(null, "¡Selecciones un item!","Error" , JOptionPane.ERROR_MESSAGE);
                        jComboBox1.showPopup();

                    } else {
                        ciudad.setIdCiudad(Integer.parseInt(this.txtCodigo.getText()));
                        ciudad.setCiudad(this.txtNombre.getText());
                        ciudad.setCp(Integer.parseInt(this.txtCP.getText()));
                        ciudad.setProvincia((Provincia) this.jComboBox1.getSelectedItem());
                        try {
                            nciudad.actualizar(ciudad);
                        } catch (SQLException ex) {
                            // VER ESTO EN LOS FORMULARIOS!!
                            Logger.getLogger(MtoDiaCiudad1_2.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        this.cargarTabla();
                        this.cargarTexto(indice);
                        this.habilitacajatexto(false);
                        this.btnNuevo.setEnabled(true);
                        this.btnEditar.setEnabled(true);
                        this.btnGrabar.setEnabled(false);
                        this.btnCancelar.setEnabled(false);
                        this.jTable1.setEnabled(true);
                        habilitaclick = false;
                        this.btnNuevo.requestFocus();
                        
                    }
                }
            }
        }
                        
}//GEN-LAST:event_btnGrabarActionPerformed

    private void txtCPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPKeyTyped
        Character caracter = new Character(evt.getKeyChar());
        Valida valida = new Valida();

        if (!valida.isNumero(caracter)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCPKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MtoDiaCiudad1_2 dialog = new MtoDiaCiudad1_2(new JDialog());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JToggleButton btnGrabar;
    private javax.swing.JToggleButton btnNuevo;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
