/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewDialog.java
 *
 * Created on 09-dic-2011, 9:22:48
 */
package Presentacion;

import Datos.ClienteDAO;
import Datos.EquipoDAO;
import Modelo.Cliente;
import Modelo.Equipo;
import Modelo.Valida;
import java.awt.Color;
import java.awt.Dialog;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.combobox.ListComboBoxModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;


/**
 *
 * @author Gisela
 */
public class MtoDiaEquipo1 extends java.awt.Dialog {

    /** Creates new form NewDialog */
    List<Equipo> equipos;
    List<Cliente> clientes;
    int indice;
    boolean nuevoequipo;
    boolean habilitaclick;
    Equipo equipo;

    public MtoDiaEquipo1(java.awt.Frame parent) {

        super(parent, "EQUIPOS", true);
        this.constructorInicial();
        }

    public MtoDiaEquipo1(Dialog parent) {

        super(parent, "EQUIPOS", true);
        this.constructorInicial();
        }
    
    private void constructorInicial(){        
        initComponents();
        this.setLocation(300, 200);
        this.setSize(600, 500);
        this.cargarTabla();
        this.listarJcombo();
        this.cargarTexto(0);
        this.setResizable(false);
        this.btnGrabar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.jComboBox1.setBackground(Color.WHITE);
        equipo = new Equipo();
        indice = 0;
        AutoCompleteDecorator.decorate(jComboBox1);
        btnNuevo.requestFocus();
    }

    private void cargarTexto(int indice) {

        if (equipos.size() > 0) {
            equipo = equipos.get(indice);
            this.txtCodigo.setText(Integer.toString(equipo.getIdEquipo()));
            this.txtNumEquipo.setText(equipo.getNroEquipo());
            this.txtMarca.setText(equipo.getMarca());
            this.txtModelo.setText(equipo.getModelo());
            this.txtSerie.setText(equipo.getNroSerie());
            this.txtDescripcion.setText(equipo.getDescripcion());
            this.jComboBox1.setSelectedIndex(equipos.get(indice).getCliente().getIdCliente() - 1);

        } else {

            limpiarCajasTexto();
            this.btnEditar.setEnabled(false);
            this.btnGrabar.setEnabled(false);
            this.btnCancelar.setEnabled(false);
        }
    }

    private void listarJcombo() {

        try {
            clientes = new ArrayList<Cliente>(new ClienteDAO().buscarTodo());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        jComboBox1.setModel(new ListComboBoxModel(clientes));

        }

    private void cargarTabla() {
        ModeloTabla tabla = new ModeloTabla();
        try {
            equipos = new ArrayList<Equipo>(new EquipoDAO().buscarTodo());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        tabla.addColumn("Id Equipo");
        tabla.addColumn("N°de Equipo");
        tabla.addColumn("Marca");
        tabla.addColumn("Modelo");
        tabla.addColumn("N°de Serie");
        tabla.addColumn("Descripción");
        tabla.addColumn("Cliente");
        tabla.setRowCount(equipos.size());

        int i = 0;
        for (Equipo equi : equipos) {
            tabla.setValueAt(equi.getIdEquipo(), i, 0);
            tabla.setValueAt(equi.getNroEquipo(), i, 1);
            tabla.setValueAt(equi.getMarca(), i, 2);
            tabla.setValueAt(equi.getModelo(), i, 3);
            tabla.setValueAt(equi.getNroSerie(), i, 4);
            tabla.setValueAt(equi.getDescripcion(), i, 5);
            tabla.setValueAt(equi.getCliente().getNombre(), i, 6);
            i++;
        }
        this.jTable1.setModel(tabla);

    }

    public void limpiarCajasTexto() {

        this.txtCodigo.setText("");
        this.txtNumEquipo.setText("");
        this.txtMarca.setText("");
        this.txtModelo.setText("");
        this.txtSerie.setText("");
        this.txtDescripcion.setText("");
        this.jComboBox1.setSelectedIndex(-1);

    }
    
    private void habilitacajatexto(boolean hab){
        this.txtDescripcion.setEnabled(hab);
        this.txtMarca.setEnabled(hab);
        this.txtNumEquipo.setEnabled(hab);
        this.txtModelo.setEnabled(hab);
        this.txtSerie.setEnabled(hab);
        this.jComboBox1.setEnabled(hab);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePickerBeanInfo1 = new org.jdesktop.swingx.JXDatePickerBeanInfo();
        jXDatePickerBeanInfo2 = new org.jdesktop.swingx.JXDatePickerBeanInfo();
        jXDatePickerBeanInfo3 = new org.jdesktop.swingx.JXDatePickerBeanInfo();
        jXDatePickerBeanInfo4 = new org.jdesktop.swingx.JXDatePickerBeanInfo();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtSerie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNumEquipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JToggleButton();
        btnEditar = new javax.swing.JToggleButton();
        btnGrabar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DE EQUIPOS"));

        txtCodigo.setText("jTextField1");
        txtCodigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigo.setEnabled(false);

        txtMarca.setText("jTextField2");
        txtMarca.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtMarca.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMarca.setEnabled(false);
        txtMarca.setNextFocusableComponent(txtModelo);

        txtModelo.setText("jTextField3");
        txtModelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtModelo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtModelo.setEnabled(false);
        txtModelo.setNextFocusableComponent(txtSerie);

        txtSerie.setText("jTextField4");
        txtSerie.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSerie.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSerie.setEnabled(false);
        txtSerie.setNextFocusableComponent(txtDescripcion);

        jLabel1.setText("Id Equipo:");

        jLabel2.setText("Marca:");

        jLabel3.setText("Modelo:");

        jLabel4.setText("N° de Serie:");

        txtDescripcion.setText("jTextField5");
        txtDescripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDescripcion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescripcion.setEnabled(false);
        txtDescripcion.setNextFocusableComponent(jComboBox1);

        jLabel5.setText("Descripción:");

        jLabel6.setText("Cliente:");

        jButton1.setText("...");
        jButton1.setEnabled(false);
        jButton1.setNextFocusableComponent(btnNuevo);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtNumEquipo.setText("jTextField2");
        txtNumEquipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNumEquipo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNumEquipo.setEnabled(false);
        txtNumEquipo.setNextFocusableComponent(txtMarca);

        jLabel8.setText("N° de Equipo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox1.setEnabled(false);
        jComboBox1.setNextFocusableComponent(jButton1);
        jComboBox1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumEquipo, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(txtSerie, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, 202, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addGap(43, 43, 43))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        /*                       */
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("OPERACIONES:"));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/componente_agregar.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setNextFocusableComponent(btnEditar);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/consultar.gif"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setNextFocusableComponent(btnGrabar);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/guardar.gif"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.setNextFocusableComponent(btnCancelar);
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cancelar.gif"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setNextFocusableComponent(txtNumEquipo);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarCajasTexto();
        nuevoequipo = true;
        this.listarJcombo();
        this.jComboBox1.setSelectedIndex(-1);
        this.btnNuevo.setEnabled(false);
        this.btnEditar.setEnabled(false);
        this.btnGrabar.setEnabled(true);
        this.btnCancelar.setEnabled(true);
        this.habilitacajatexto(true);
        this.jButton1.setEnabled(true);
        this.jTable1.setEnabled(false);
        this.txtNumEquipo.requestFocus();
        habilitaclick=true;
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        nuevoequipo = false;
        habilitaclick=true;
        this.btnEditar.setEnabled(false);
        this.btnNuevo.setEnabled(false);
        this.btnGrabar.setEnabled(true);
        this.btnCancelar.setEnabled(true);
        this.habilitacajatexto(true);
        this.jButton1.setEnabled(true);
        this.jTable1.setEnabled(false);
        this.txtNumEquipo.requestFocus();
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        EquipoDAO nequipo = new EquipoDAO();
        Valida validar = new Valida();

        if (nuevoequipo == true) {

            if (validar.isCampoVacio(this.txtNumEquipo.getText())) {
                JOptionPane.showMessageDialog(null,"¡Faltan Completar Datos!","Error" , JOptionPane.ERROR_MESSAGE);
                txtNumEquipo.requestFocus();
            } else {
                if (validar.isCampoVacio(this.txtMarca.getText())) {
                    JOptionPane.showMessageDialog(null,"¡Faltan Completar Datos!","Error" , JOptionPane.ERROR_MESSAGE);
                    txtMarca.requestFocus();
                } else {
                    if (validar.isCampoVacio(txtModelo.getText())) {
                        JOptionPane.showMessageDialog(null,"¡Faltan Completar Datos!","Error" , JOptionPane.ERROR_MESSAGE);
                        txtModelo.requestFocus();
                    } else {
                        if (validar.isCampoVacio(txtSerie.getText())) {
                            JOptionPane.showMessageDialog(null,"¡Faltan Completar Datos!","Error" , JOptionPane.ERROR_MESSAGE);
                            txtSerie.requestFocus();
                        } else {
                            if (validar.isCampoVacio(txtDescripcion.getText())) {
                                JOptionPane.showMessageDialog(null,"¡Faltan Completar Datos!","Error" , JOptionPane.ERROR_MESSAGE);
                                txtDescripcion.requestFocus();
                            } else {

                                if (jComboBox1.getSelectedIndex() == -1) {
                                    JOptionPane.showMessageDialog(null, "¡Selecciones un item!","Error" , JOptionPane.ERROR_MESSAGE);
                                    jComboBox1.showPopup();

                                } else {

                                    equipo.setNroEquipo(this.txtNumEquipo.getText());
                                    equipo.setMarca(this.txtMarca.getText());
                                    equipo.setModelo((this.txtModelo.getText()));
                                    equipo.setNroSerie((this.txtSerie.getText()));
                                    equipo.setDescripcion((this.txtDescripcion.getText()));
                                    equipo.setCliente((Cliente) this.jComboBox1.getSelectedItem());

                                    System.out.println(equipo);

                                    try {
                                        nequipo.agregar(equipo);
                                    } catch (SQLException ex) {
                                        Logger.getLogger(MtoDiaCiudad1_2.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                    this.cargarTabla();
                                    indice = (equipos.size() - 1);
                                    this.cargarTexto(indice);
                                    this.btnNuevo.setEnabled(true);
                                    this.btnEditar.setEnabled(true);
                                    this.btnGrabar.setEnabled(false);
                                    this.btnCancelar.setEnabled(false);
                                    this.jButton1.setEnabled(false);
                                    this.jTable1.setEnabled(true);
                                    habilitaclick=false;
                                    this.habilitacajatexto(false);
                                    
                                }
                            }
                        }
                    }
                }
            }

        } else {

             if (validar.isCampoVacio(this.txtNumEquipo.getText())) {
                JOptionPane.showMessageDialog(null,"¡Faltan Completar Datos!","Error" , JOptionPane.ERROR_MESSAGE);
                txtNumEquipo.requestFocus();
            } else {
                if (validar.isCampoVacio(this.txtMarca.getText())) {
                    JOptionPane.showMessageDialog(null,"¡Faltan Completar Datos!","Error" , JOptionPane.ERROR_MESSAGE);
                    txtMarca.requestFocus();
                } else {
                    if (validar.isCampoVacio(txtModelo.getText())) {
                        JOptionPane.showMessageDialog(null,"¡Faltan Completar Datos!","Error" , JOptionPane.ERROR_MESSAGE);
                        txtModelo.requestFocus();
                    } else {
                        if (validar.isCampoVacio(txtSerie.getText())) {
                            JOptionPane.showMessageDialog(null,"¡Faltan Completar Datos!","Error" , JOptionPane.ERROR_MESSAGE);
                            txtSerie.requestFocus();
                        } else {
                            if (validar.isCampoVacio(txtDescripcion.getText())) {
                                JOptionPane.showMessageDialog(null,"¡Faltan Completar Datos!","Error" , JOptionPane.ERROR_MESSAGE);
                                txtDescripcion.requestFocus();
                            } else {

                                if (jComboBox1.getSelectedIndex() == -1) {
                                    JOptionPane.showMessageDialog(null, "¡Selecciones un item!","Error" , JOptionPane.ERROR_MESSAGE);
                                    jComboBox1.showPopup();

                                } else {
            
            equipo = equipos.get(indice);

            equipo.setIdEquipo(Integer.parseInt(this.txtCodigo.getText()));
            equipo.setNroEquipo(this.txtNumEquipo.getText());
            equipo.setMarca(this.txtMarca.getText());
            equipo.setModelo((this.txtModelo.getText()));
            equipo.setNroSerie((this.txtSerie.getText()));
            equipo.setDescripcion((this.txtDescripcion.getText()));
            equipo.setCliente((Cliente) this.jComboBox1.getSelectedItem());

            try {
                nequipo.actualizar(equipo);
            } catch (SQLException ex) {
                Logger.getLogger(MtoDiaCiudad1_2.class.getName()).log(Level.SEVERE, null, ex);
            }

            this.cargarTabla();
            this.cargarTexto(indice);
            this.habilitacajatexto(false);
            this.btnNuevo.setEnabled(true);
            this.btnEditar.setEnabled(true);
            this.btnGrabar.setEnabled(false);
            this.btnCancelar.setEnabled(false);
            this.jButton1.setEnabled(false); 
            this.jTable1.setEnabled(true);
            habilitaclick=false;
                                }
                            }
                        }
                    }
                }
             }
        

        }
        
       
        
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (equipos.size() > 0) {

            if (nuevoequipo == true) {
                this.listarJcombo();
                this.cargarTexto(indice);
                this.btnNuevo.setEnabled(true);
                this.btnCancelar.setEnabled(false);
                this.btnGrabar.setEnabled(false);
                if (equipos.size() > 0) {
                    this.btnEditar.setEnabled(true);
                } else {
                    this.btnEditar.setEnabled(false);
                }
            } else {

                this.cargarTexto(indice);
                this.btnNuevo.setEnabled(true);
                this.btnEditar.setEnabled(true);
                this.btnGrabar.setEnabled(false);
                this.btnCancelar.setEnabled(false);
            }
        } else {
            limpiarCajasTexto();
            this.btnGrabar.setEnabled(false);
            this.btnCancelar.setEnabled(false);
            
        }
        this.habilitacajatexto(false);
        this.jButton1.setEnabled(false);
        this.jTable1.setEnabled(true);
        habilitaclick = false;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MtoDiaCliente nuevoCli = new MtoDiaCliente(this);
        nuevoCli.setVisible(true);
        this.listarJcombo();
        this.jComboBox1.setSelectedIndex(-1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

       if(habilitaclick==true){
           
       }else{
            indice = this.jTable1.getSelectedRow();
            equipo = equipos.get(indice);
            this.cargarTexto(indice);
       }
    }//GEN-LAST:event_jTable1MouseClicked

    
    
    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                MtoDiaEquipo1 dialog = new MtoDiaEquipo1(new java.awt.Frame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JToggleButton btnGrabar;
    private javax.swing.JToggleButton btnNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePickerBeanInfo jXDatePickerBeanInfo1;
    private org.jdesktop.swingx.JXDatePickerBeanInfo jXDatePickerBeanInfo2;
    private org.jdesktop.swingx.JXDatePickerBeanInfo jXDatePickerBeanInfo3;
    private org.jdesktop.swingx.JXDatePickerBeanInfo jXDatePickerBeanInfo4;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNumEquipo;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables
}
